### ISSUE TITLE
com.sportradar.livedata.sdk.proto.dto.incoming.livescout.Login Missing this POJO

### ISSUE THREAD

**Issue by fofohi** [sportradar/LivedataSdkJava#4]
I cant find this class in your SDK and Do u have JAVA8 version SDK?

**Comment by aklevanets** [comment]
Hi, at the moment we are still supporting old version of SDK - Bookmaker SDK. Can be found here: https://sdk.sportradar.com/bookmaker/java
No longer be maintained after 01.07.2023

Regarding missing class - during building it will be generated from [xsd](https://github.com/sportradar/LivedataSdkJava/blob/main/sdk/src/main/xsd/ScoutRequest.xsd).

**Comment by fofohi** [comment]
Thank u
